"""schema

Revision ID: ce6420cca6e9
Revises: 
Create Date: 2026-02-18 15:10:03.182157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'schema'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Integer(), server_default="1", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name=op.f("username")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f("username"), "user", type_="unique")
    op.drop_table("user")
   
    # ### end Alembic commands ###